Revert "Change way to initialize Player's position"
This reverts commit aa9f3b92470b88df336162f4414306888a71a13d.
初期化の位置ずらしても同じことが起きてるから原因はもっと別にあるのか
にしても意味ワカんね
error: cannot convert ‘map::Map’ to ‘std::size_t {aka long unsigned int}’ in initialization
     player_{}
             ^